'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Download,Upload,BookOpen,Dumbbell,Code2,Leaf,Music,Heart,PenTool,Footprints,Flame,Award,Check,MoreHorizontal,Minus,Sparkles,Grid2X2,Cloud,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tooltip,TooltipTrigger,TooltipContent,TooltipProvider} from '@/components/ui/tooltip';
import {Toaster,toast} from 'sonner';
import {Habit,calendar,statistics,level,cellColor,today,validateHabits} from '@/lib/habits';
import {download,exportCards} from '@/lib/export';
const icons={book:BookOpen,sport:Dumbbell,code:Code2,plant:Leaf,music:Music,heart:Heart,draw:PenTool,walk:Footprints};
const iconLabels={book:'Lecture',sport:'Sport',code:'Code',plant:'Jardin',music:'Musique',heart:'Bien-être',draw:'Création',walk:'Marche'};
const colors=['#7155e8','#138d65','#e57537','#207ac1','#cc4980','#b39116','#555e78','#d44040'];
function Icon({value,size=24}:{value:string;size?:number}){if(value.startsWith('emoji:'))return <span style={{fontSize:size}}>{value.slice(6)}</span>;const C=icons[value as keyof typeof icons]||Sparkles;return <C size={size}/>;}
const number=(n:number)=>n.toLocaleString('fr-FR',{maximumFractionDigits:2});
const pretty=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Paris'});
function Heatmap({habit,year,onDay}:{habit:Habit;year:number;onDay:(d:string)=>void}){const grid=calendar(year),s=statistics(habit,year),now=today();let prev=-1;return <div className="map-scroll"><div className="map-wrap"><div className="month-row">{Array.from({length:grid.length/7},(_,w)=>{const d=grid.slice(w*7,w*7+7).find(Boolean);const m=d?Number(d.slice(5,7)):-1;const show=m!==prev;prev=m;return <span key={w}>{show&&m>0?['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'][m-1]:''}</span>;})}</div><div className="map-line"><div className="week-labels"><span>Lun</span><span>Mer</span><span>Ven</span></div><div className="heatmap" style={{gridTemplateColumns:`repeat(${grid.length/7},1fr)`}}>{grid.map((d,i)=>{if(!d)return <span key={i}/>;const future=d>now,before=d<habit.startDate,n=habit.entries[d]?.count||0;return <Tooltip key={d}><TooltipTrigger asChild><button type="button" className={'cell'+(d===now?' current-day':'')+(future||before?' unavailable':'')} disabled={future||before} style={{background:future||before?'#f5f6fa':cellColor(habit.color,level(n,s.mean))}} onClick={()=>onDay(d)} aria-label={pretty(d)+', '+n+' actions'+(before?', avant le début du suivi':future?', jour futur':'')}/></TooltipTrigger><TooltipContent>{pretty(d)} · {before?'Avant le suivi':future?'Jour futur':n+' actions'}{habit.entries[d]?.note&&<div>{habit.entries[d].note.slice(0,120)}</div>}</TooltipContent></Tooltip>;})}</div></div></div></div>;}
export default function Tracker(){
 const [tasks,setTasks]=useState<Habit[]>([]),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[failed,setFailed]=useState(false),[year,setYear]=useState(Number(today().slice(0,4))),[filter,setFilter]=useState('all');
 const revision=useRef(0),file=useRef<HTMLInputElement>(null),busy=useRef(false);
 const [editor,setEditor]=useState<Habit|null>(null),[editing,setEditing]=useState(false),[entry,setEntry]=useState<{id:string;date:string;count:number;note:string}|null>(null),[confirm,setConfirm]=useState<{title:string;message:string;run:()=>void}|null>(null),[exporting,setExporting]=useState(false);
 const date=today(),thisYear=Number(date.slice(0,4));
 async function load(){setError('');try{const r=await fetch('/api/journal',{cache:'no-store'}),d=await r.json() as {error?:string;tasks:Habit[];revision:number};if(!r.ok)throw Error(d.error);setTasks(validateHabits(d.tasks));revision.current=d.revision;setLoaded(true);setFailed(false);}catch(e){setError(e instanceof Error?e.message:'Chargement impossible.');}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!failed&&!saving)return;const listener=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[failed,saving]);
 async function commit(next:Habit[]){if(busy.current)return;busy.current=true;setTasks(next);setSaving(true);setError('');try{const r=await fetch('/api/journal',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({tasks:next,revision:revision.current})}),d=await r.json() as {error?:string;tasks:Habit[];revision:number};if(!r.ok)throw Error(d.error);revision.current=d.revision;setFailed(false);}catch(e){setFailed(true);setError(e instanceof Error?e.message:'Sauvegarde impossible.');}finally{busy.current=false;setSaving(false);}}
 const locked=saving||!loaded||failed;
 function start(h?:Habit){setEditing(Boolean(h));setEditor(h?{...h}:{id:crypto.randomUUID(),name:'',icon:'book',color:colors[tasks.length%colors.length],startDate:date,entries:{}});}
 function setCount(h:Habit,d:string,count:number,note=h.entries[d]?.note||''){if(locked)return;const next={...h,entries:{...h.entries,[d]:{count,note}}};void commit(tasks.map(t=>t.id===h.id?next:t));}
 function backup(){download(new Blob([JSON.stringify({format:'micro-habitudes',version:1,exportedAt:new Date().toISOString(),tasks},null,2)],{type:'application/json'}),'micro-sauvegarde-'+date+'.json');toast.success('Fichier de sauvegarde exporté');}
 async function restore(f:File){try{if(f.size>4000000)throw Error('Ce fichier est trop volumineux.');const d=JSON.parse(await f.text());if(d.format!=='micro-habitudes'||d.version!==1)throw Error('Ce fichier n’est pas une sauvegarde Micro.');const imported=validateHabits(d.tasks);setConfirm({title:'Restaurer cette sauvegarde ?',message:`${imported.length} tâche(s) remplaceront ton suivi actuel. Exporte d’abord une sauvegarde si tu veux le conserver.`,run:()=>{setFilter('all');void commit(imported);}});}catch(e){toast.error(e instanceof Error?e.message:'Fichier invalide.');}}
 async function image(h?:Habit){if(exporting)return;setExporting(true);try{await exportCards(h?[h]:tasks,year);toast.success('Carte annuelle exportée');}catch(e){toast.error(e instanceof Error?e.message:'Export impossible.');}finally{setExporting(false);}}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const abort=new AbortController();try{Promise.resolve(context.registerTool({name:'read_habit_summary',title:'Lire le suivi des habitudes',description:'Lire les tâches et leurs statistiques annuelles sans modifier les données.',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:1900,maximum:2200}},required:['year'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:{year:number})=>{if(!Number.isInteger(input.year)||input.year<1900||input.year>2200)throw Error('Année invalide.');if(!loaded)throw Error('Suivi non chargé.');return tasks.map(t=>({id:t.id,name:t.name,...statistics(t,input.year)}));}},{signal:abort.signal})).catch(()=>{});}catch{}return()=>abort.abort();},[tasks,loaded]);
 const shown=filter==='all'?tasks:tasks.filter(t=>t.id===filter),total=tasks.reduce((n,h)=>n+statistics(h,year).total,0),done=tasks.filter(h=>(h.entries[date]?.count||0)>0).length;
 const years=Array.from(new Set([thisYear,year,...tasks.map(t=>Number(t.startDate.slice(0,4)))]));const first=Math.min(...years);
 return <TooltipProvider delayDuration={140}><div className="app"><header className="topbar"><a className="brand" href="/" aria-label="Micro, accueil"><span className="brand-mark"><Grid2X2 size={21}/></span>micro<span className="brand-dot">.</span></a><div className="edition">INKTOBER / 03 <span>MINIATURE</span></div><div className="save-state" role="status"><Cloud size={17}/>{saving?'Enregistrement…':failed?'À sauvegarder':loaded?'Suivi sauvegardé':'Chargement…'}</div></header>
 <main><section className="intro"><div><p className="eyebrow">TON JOURNAL D’HABITUDES</p><h1>Petites actions.<br/><span>Année après année.</span></h1></div><div className="intro-side"><span className="year-stamp">{year}</span><div className="date-label">{pretty(date)}</div></div></section>
 <div className="overview"><div><span className="stat-number">{tasks.length.toString().padStart(2,'0')}</span><span>habitudes suivies</span></div><div><span className="stat-number">{number(total)}</span><span>actions en {year}</span></div><div><span className="stat-number">{done}<small> / {tasks.length}</small></span><span>habitudes actives aujourd’hui</span></div><div className="overview-note"><span className="mini-squares">{[0,1,2,3,4].map(l=><i key={l} style={{background:cellColor('#7155e8',l)}}/>)}</span><span>Chaque carré compte.</span></div></div>
 <div className="workspace-toolbar"><div className="toolbar-left"><Select value={String(year)} onValueChange={v=>setYear(Number(v))}><SelectTrigger aria-label="Année affichée"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:thisYear-first+2},(_,i)=>first+i).reverse().map(y=><SelectItem value={String(y)} key={y}>{y}</SelectItem>)}</SelectContent></Select>{tasks.length>0&&<Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filtrer les habitudes"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les habitudes</SelectItem>{tasks.map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select>}</div><div className="toolbar-right"><button className="btn secondary" disabled={!tasks.length||exporting} onClick={()=>void image()}><Download size={17}/>{exporting?'Export…':'Carte annuelle'}</button><button className="btn primary" disabled={locked} onClick={()=>start()}><Plus size={18}/>Nouvelle habitude</button></div></div>
 {error&&<div className="error-panel" role="alert"><p>{error}</p>{failed?<><button className="btn secondary" disabled={saving} onClick={()=>void commit(tasks)}><RefreshCw size={16}/>Réessayer</button><button className="btn secondary" onClick={backup}>Exporter mes données</button></>:<button className="btn secondary" onClick={()=>void load()}>Réessayer</button>}</div>}
 {!loaded&&!error&&<div className="empty">Chargement de ton journal…</div>}
 {loaded&&tasks.length===0&&<section className="empty"><div className="empty-preview" aria-hidden="true">{Array.from({length:126},(_,i)=><i key={i} style={{background:i<80?cellColor('#7155e8',(i*7+3)%5):'#edeef3'}}/>)}</div><p className="eyebrow">UNE ANNÉE COMMENCE PAR UNE CASE</p><h2>Quelle petite action veux-tu suivre ?</h2><p>Lecture, sport, code… Choisis une habitude,<br/>puis donne-lui une couleur.</p><button className="btn primary" disabled={locked} onClick={()=>start()}><Plus size={18}/>Créer ma première habitude</button><span className="preview-label">Grille d’illustration · aucun historique créé</span></section>}
 <div className="habit-list">{shown.map((h,i)=>{const s=statistics(h,year),n=h.entries[date]?.count||0;return <article className="habit-card" data-habit-id={h.id} key={h.id} style={{'--habit-color':h.color,animationDelay:i*50+'ms'} as React.CSSProperties}><div className="habit-header"><div className="habit-title"><span className="habit-icon" style={{color:h.color,background:cellColor(h.color,1)}}><Icon value={h.icon}/></span><div><h2>{h.name}</h2><p>Depuis le {pretty(h.startDate)}</p></div></div><div className="habit-actions"><div className="today-counter"><button aria-label={'Retirer une action à '+h.name} disabled={locked||n===0} onClick={()=>setCount(h,date,n-1)}><Minus size={16}/></button><button className="count-value" onClick={()=>setEntry({id:h.id,date,count:n,note:h.entries[date]?.note||''})} disabled={locked}><strong>{n}</strong><span>aujourd’hui</span></button><button className="increment" aria-label={'Ajouter une action à '+h.name} disabled={locked||n>=1000000000} onClick={()=>setCount(h,date,n+1)}><Plus size={18}/></button></div><button className="icon-btn" aria-label={'Configurer '+h.name} disabled={locked} onClick={()=>start(h)}><MoreHorizontal size={21}/></button></div></div>
 <Heatmap habit={h} year={year} onDay={d=>{if(!locked)setEntry({id:h.id,date:d,count:h.entries[d]?.count||0,note:h.entries[d]?.note||''});}}/>
 <div className="card-bottom"><div className="habit-stats"><span><strong>{number(s.total)}</strong> actions</span><span><strong>{s.active}</strong> jours actifs</span><Tooltip><TooltipTrigger asChild><span tabIndex={0}><strong>{number(s.mean)}</strong> / jour</span></TooltipTrigger><TooltipContent>Total depuis le début ÷ {s.elapsed} jours, jours à zéro compris.</TooltipContent></Tooltip></div><div className="legend"><span>Moins</span>{[0,1,2,3,4].map(l=><i key={l} style={{background:cellColor(h.color,l)}}/>)}<span>Plus</span></div></div><div className="streak-row"><span><Flame size={17}/><strong>{s.current}</strong> jours en cours</span><span><Award size={17}/><strong>{s.best}</strong> jours · record {year}</span><span className="global-record">Record global : {s.allBest} jours</span><button className="text-btn" disabled={exporting} onClick={()=>void image(h)}><Download size={15}/>Exporter cette carte</button></div></article>;})}</div>
 <footer><div><strong>Ton rythme, ta couleur.</strong><p>La teinte compare chaque journée à ta moyenne depuis le début du suivi.<br/>Les jours à zéro comptent. Les jours futurs et avant le suivi sont exclus.</p></div><div className="backup-actions"><button className="btn secondary" disabled={!loaded} onClick={backup}><Download size={16}/>Sauvegarde JSON</button><button className="btn secondary" disabled={locked} onClick={()=>file.current?.click()}><Upload size={16}/>Restaurer</button><input hidden type="file" accept=".json,application/json" ref={file} onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f);e.target.value='';}}/><small>Sauvegarde privée en ligne + fichier de secours.</small></div></footer>
 </main>
 <Dialog open={Boolean(editor)} onOpenChange={v=>{if(!v)setEditor(null);}}><DialogContent className="micro-dialog"><DialogTitle>{editing?'Personnaliser l’habitude':'Une nouvelle petite action'}</DialogTitle><DialogDescription>Un nom, un symbole, une couleur. À toi de choisir.</DialogDescription>{editor&&<form onSubmit={e=>{e.preventDefault();try{const clean=validateHabits([editor])[0];void commit(editing?tasks.map(t=>t.id===clean.id?clean:t):[...tasks,clean]);setEditor(null);}catch(err){toast.error(err instanceof Error?err.message:'Habitude invalide.');}}}><label>Nom de l’habitude<input required autoFocus maxLength={80} placeholder="Ex. Lire quelques pages" value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label>Date de début<input type="date" required min="1900-01-01" max={date} value={editor.startDate} onChange={e=>setEditor({...editor,startDate:e.target.value})}/></label><p className="field-label">Symbole</p><div className="icon-picker">{Object.keys(icons).map(k=><button key={k} type="button" aria-label={iconLabels[k as keyof typeof iconLabels]} aria-pressed={editor.icon===k} className={editor.icon===k?'selected':''} onClick={()=>setEditor({...editor,icon:k})}><Icon value={k} size={21}/></button>)}</div><label>Ou ton émoji<input maxLength={12} placeholder="🌱" value={editor.icon.startsWith('emoji:')?editor.icon.slice(6):''} onChange={e=>setEditor({...editor,icon:e.target.value?'emoji:'+e.target.value:'book'})}/></label><p className="field-label">Couleur</p><div className="color-picker">{colors.map(c=><button type="button" key={c} aria-label={'Couleur '+c} aria-pressed={editor.color===c} style={{background:c}} className={editor.color===c?'selected':''} onClick={()=>setEditor({...editor,color:c})}>{editor.color===c&&<Check size={18}/>}</button>)}<input type="color" aria-label="Couleur personnalisée" value={editor.color} onChange={e=>setEditor({...editor,color:e.target.value})}/></div><div className="form-footer">{editing&&<button type="button" className="danger-text" onClick={()=>{const id=editor.id;setEditor(null);setConfirm({title:'Supprimer cette habitude ?',message:'Son historique sera supprimé. Une sauvegarde exportée permet de le restaurer.',run:()=>{setFilter('all');void commit(tasks.filter(t=>t.id!==id));}});}}>Supprimer</button>}<button className="btn primary" disabled={locked} type="submit">{editing?'Enregistrer':'Créer l’habitude'}</button></div></form>}</DialogContent></Dialog>
 <Dialog open={Boolean(entry)} onOpenChange={v=>{if(!v)setEntry(null);}}><DialogContent className="micro-dialog"><DialogTitle>{entry?pretty(entry.date):''}</DialogTitle><DialogDescription>{tasks.find(t=>t.id===entry?.id)?.name} · Ajuste le nombre d’actions réalisées.</DialogDescription>{entry&&<form onSubmit={e=>{e.preventDefault();const h=tasks.find(t=>t.id===entry.id);if(h){setCount(h,entry.date,entry.count,entry.note);setEntry(null);}}}><label>Nombre d’actions<input required type="number" min={0} max={1000000000} step={1} value={entry.count} onChange={e=>setEntry({...entry,count:Number(e.target.value)})}/></label><label>Note du jour <span className="optional">facultative</span><textarea maxLength={2000} rows={4} placeholder="Un détail à garder…" value={entry.note} onChange={e=>setEntry({...entry,note:e.target.value})}/></label><div className="form-footer"><button className="btn primary" disabled={locked} type="submit">Enregistrer la journée</button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={Boolean(confirm)} onOpenChange={v=>{if(!v)setConfirm(null);}}><AlertDialogContent><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.message}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction onClick={()=>confirm?.run()}>Confirmer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <div hidden aria-hidden="true">{tasks.map(h=><span data-export-icon={h.id} key={h.id}><Icon value={h.icon}/></span>)}</div><Toaster richColors position="bottom-right"/></div></TooltipProvider>;
}
