import {Habit,calendar,statistics,level,cellColor,today} from './habits';
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function exportCards(tasks:Habit[],year:number){
 const iconImages = new Map<string,HTMLImageElement>();
 for(const h of tasks){const svg=document.querySelector('[data-export-icon="'+CSS.escape(h.id)+'"] svg');if(!svg)continue;const clone=svg.cloneNode(true) as SVGElement;clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('color',h.color);clone.setAttribute('width','40');clone.setAttribute('height','40');const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(clone));await img.decode();iconImages.set(h.id,img);}
 const batch=tasks.length>12?tasks.map(t=>[t]):[tasks];
 for(const group of batch){const c=document.createElement('canvas');c.width=1600;c.height=240+group.length*410;const g=c.getContext('2d');if(!g)throw Error('Export indisponible.');g.fillStyle='#f5f6fa';g.fillRect(0,0,c.width,c.height);g.fillStyle='#191c29';g.font='bold 58px sans-serif';g.fillText('micro.',80,100);g.font='28px sans-serif';g.fillStyle='#606575';g.fillText('MON ANNÉE EN PETITES ACTIONS',80,155);g.textAlign='right';g.font='bold 60px sans-serif';g.fillStyle='#191c29';g.fillText(String(year),1520,115);g.textAlign='left';
 group.forEach((h,i)=>{const y=210+i*410,s=statistics(h,year),grid=calendar(year);g.fillStyle='#ffffff';g.beginPath();g.roundRect(55,y,1490,380,24);g.fill();g.fillStyle=h.color;g.beginPath();g.roundRect(85,y+27,8,44,4);g.fill();g.fillStyle='#191c29';g.font='bold 34px sans-serif';const icon=iconImages.get(h.id);if(icon)g.drawImage(icon,109,y+34,32,32);g.fillText((h.icon.startsWith('emoji:')?h.icon.slice(6)+' ':'')+h.name,icon?155:115,y+64,icon?960:1000);g.textAlign='right';g.font='bold 25px sans-serif';g.fillStyle=h.color;g.fillText('★ RECORD '+s.best+' JOURS',1510,y+60);g.textAlign='left';
 const step=25,size=20;grid.forEach((d,j)=>{if(!d)return;const future=d>today()||d<h.startDate;g.fillStyle=future?'#f5f6fa':cellColor(h.color,level(h.entries[d]?.count||0,s.mean));g.beginPath();g.roundRect(110+Math.floor(j/7)*step,y+107+(j%7)*step,size,size,4);g.fill();});
 g.font='25px sans-serif';g.fillStyle='#606575';g.fillText(s.total+' actions   ·   '+s.active+' jours actifs   ·   moyenne du suivi '+s.mean.toLocaleString('fr-FR',{maximumFractionDigits:2})+'/jour',110,y+325);});
 await new Promise<void>((resolve,reject)=>c.toBlob(b=>{if(!b){reject(Error('Export indisponible.'));return;}download(b,'micro-'+year+(group.length===1?'-'+group[0].name.replace(/[^a-zA-Z0-9]/g,'_'):'')+'.png');resolve();},'image/png'));
 }
}
